### PR TITLE
fixup fast-usdc-beta and silent failure that let it through

### LINKED ISSUE #223: runner swallows test failures
https://github.com/Agoric/agoric-3-proposals/pull/210/ changed the `execSync` that runs the proposal test into a `spawnSync` without checking the result status code.

We discovered this in debugging https://github.com/Agoric/agoric-3-proposals/pull/220 , which turned out to have failures even though it passed CI:
```
[87:fast-usdc-beta] Running test.sh.

  Uncaught exception in test/deploy.test.js

  Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@endo/init' imported from /usr/src/proposals/87:fast-usdc-beta/test/deploy.test.js

  ✘ test/deploy.test.js exited with a non-zero exit code: 1
  ─
```

7a931c44d886a2d0743f2160740a8da38d798d42 reads the status code and [a run shows correct failure](https://github.com/Agoric/agoric-3-proposals/actions/runs/13425067512/job/37506331687?pr=222). I can't merge that commit until true failure is addressed.

### PR DESCRIPTION
**Pull request by turadg**
Closes #223

Corrects a bug with the test runner

And fixes proposal 87 to pass. CI is still running but the eval has a test too that is passing,
```
#2772 78.50 SUCCESS: TEST: ensure contract started:  is not equal to {"blockHeight":"1418","values":["{\"poolAccount\":\"agoric1hp6dwm4c820nwhq4hdpxjx5h9nac2gcy7fe0slp6lwnfzm76vnwqv3gf59\",\"settlementAccount\":\"agoric12rqzc0976vhxajjwqj76l7x6m0jpvpjf4mk54wyjfyemn09l6xuq7mvvpj\"}"]}
#2772 78.50 [87:fast-usdc-beta] Eval completed. Running 10 blocks and exiting.
```

### CODE REVIEW

**Comment by turadg** [comment]
@dckc one problem is the oracle addresses aren't provisioned wallets in a3p:
```
	2025-02-20T02:35:26.458Z SwingSet: ls: v11: Error: "nameKey" not found: "agoric1ym488t6j24x3ys3va3452ftx44lhs64rz8pu7h"
	2025-02-20T02:35:26.460Z SwingSet: ls: v11: Error: "nameKey" not found: "agoric17crpkfxarq658e9ddru2petrfr0fhjzvjfccq9"
	2025-02-20T02:35:26.463Z SwingSet: ls: v11: Error: "nameKey" not found: "agoric1s5yawjgj6xcw4ea5r2x4cjrnkprmd0fcun2tyk"
```

**Comment by dckc** [comment]
yeah;  kind of a known issue:

 - https://github.com/Agoric/agoric-sdk/issues/8441

**Review by mujahidkay — APPROVED** [review]

File: packages/synthetic-chain/src/cli/run.ts [hunk 1]
```diff
@@ -97,6 +99,11 @@ export const runTestImage = ({
   } finally {
     removeTempFileCallback();
   }
+
+  if (runResult.status !== 0) {
+    console.error(`Run of ${name} failed with exit code ${runResult.status}`);
```
Comment (usmanmani1122) [inline packages/synthetic-chain/src/cli/run.ts:104]: Isn't `name` defined in the try catch block? This will throw `ReferenceError` in case of failure...
And why not add this `if` block inside the `try` block below the `spawnSync` invocation?
